### ISSUE TITLE
Can we add more colours?

### ISSUE THREAD

**Issue by jacktuck** [aksakalli/gtop#10]
Atm if you have >6 cores, colours get reused and the graph is a bit confusing.

Would you accept a PR to add more?

<img src="http://i.imgur.com/vsKmdBw.png">

It looks great on my local machine though (4 cores), really nice work! :)

**Comment by aksakalli** [comment]
@jacktuck I am not sure about how informative it is to plot more than 8 cores :confused: or distinguish them one by one

**Comment by murrayf** [comment]
It would be nice to add at least two more colors for an eight core processor... ;)
Thanks,
Alberto.
