### ISSUE TITLE
ZSH: Command not found: gtop

### ISSUE THREAD

**Issue by ultimatevegance** [aksakalli/gtop#102]
#### Environment

- OS:MacOS 10.15.7
- Node version: (`$ node --version`) v14.12.0
- gtop version: (`$ npm info gtop version`).1.0.2

#### Description

zsh: command not found: gtop
![image](https://user-images.githubusercontent.com/9568495/94356679-a1511380-00c3-11eb-9d29-75f647fffe74.png)

**Comment by JohannLange** [comment]
What is the output of `which gtop` if you execute the command in bash?
And is the folder `/usr/local/Cellar` part of your `$PATH` variable in zsh?

Otherwise, try `sudo npm install gtop -g` to install `gtop` into `/usr/localbin`
