### ISSUE TITLE
Words on *BSD compatibility?

### ISSUE THREAD

**Issue by AndreiSva** [aksakalli/gtop#104]
On my main computer I dual boot Linux, OpenBSD and FreeBSD. I love all those operating systems and recently I wanted to install gtop on my OpenBSD install I noticed that there isn't any official support for it. Is this something that can be overcome or does gtop only work on Linux specifically?

**Comment by aksakalli** [comment]
It should work just fine in different linux distros. Please provide some feedback if you encounter any problems.
