### ISSUE TITLE
how to remove all the things that were installed?

### ISSUE THREAD

**Issue by SYK-08** [aksakalli/gtop#108]
#### Environment

- OS: Linux Mint XFCE 20.1
- Node version: 10.19.0
- gtop version:1.1.0
#### Description

*A description of the issue*
I am not able to uninstall the packages that were installed. Please add in the readme showing how to uninstall this entirely.

**Comment by aksakalli** [comment]
```bash
npm uninstall -g gtop
```
[the npm docs](https://docs.npmjs.com/uninstalling-packages-and-dependencies#example)
