### ISSUE TITLE
Apple M1 info is not right

### ISSUE THREAD

**Issue by forfuns** [aksakalli/gtop#112]
#### Environment

- OS: macos 11.5.1 
- Node version: v15.11.0
- gtop version: 1.1.1

#### Description

I use `gtop` with macbook pro (M1) , only `CPU History` and `Processes` like right.

that `Memory` and `Disk usage` show me the information is absolute wrong

because contrast `htop` show me look like truth

![企业微信20210810-182622](https://user-images.githubusercontent.com/1745525/128851412-0ba53d28-ac7f-4752-9553-9c808a4f1115.png)

**Comment by aksakalli** [comment]
with `v1.1.1`, we upgraded the `systeminformation` version. It should support Apple M1.
