### ISSUE TITLE
remainColor == 'black' seems like a bad default for the donuts

### ISSUE THREAD

**Issue by shivanshu3** [aksakalli/gtop#114]
#### Environment

- OS: 5.14.6-arch1-1
- Node version: v16.9.1
- gtop version: 1.1.1

#### Description

A lot of terminal emulators have a black background. And since the donut background color is also black, there is no contrast between these 2 colors which isn't ideal for the UX. I suggest setting it to blue.

Long term it would be nice to allow the user to create a `~/.gtop_profile` file to allow such customizations as well, but that's probably a separate issue.

**Comment by aksakalli** [comment]
thank you for reporting this. There is already an issue for customizing colors. #62

**Comment by shivanshu3** [comment]
@aksakalli This issue is about changing the default donut color though. The default colors should work well for majority of the people right? We don't want a new user to download this tool and think it's broken and then uninstall it.
