### ISSUE TITLE
100% CPU usage on Windows 10

### ISSUE THREAD

**Issue by niutech** [aksakalli/gtop#117]
#### Environment

- OS: Windows 10
- Node version: v16.13.0
- gtop version: 1.1.2

#### Description

gtop is constantly using 100% of my CPU time, making it unusable:

![gtop](https://user-images.githubusercontent.com/384997/146981293-7894776a-5629-4015-9d68-ea7d210b301a.png)

![gtop cpu](https://user-images.githubusercontent.com/384997/146981272-bd00fa9f-fba9-472a-b465-0359e9485094.png)

What is more, it doesn't show itself on the process list.

This could be a part of issue #12.

**Comment by aksakalli** [comment]
I admit that the NodeJS environment and underlying tech for `gtop` is not so performant. see #12

100% usage is still too high. Try to use the latest NodeJS version in a better machine. You can alternatively use an implementation in a more performant language such as Rust (`ytop`) & Golang (`gotop`).
