### ISSUE TITLE
square mark in windows 10(Chinese)

### ISSUE THREAD

**Issue by navono** [aksakalli/gtop#15]
#### Environment

- OS: Win10 x64
- Node version: (`$ node --version`) v8.0
- gtop version: (`$ npm info gtop version`) 0.1.4

#### Description

I tried this command :
> gtop LANG=en_US.utf8 TERM=xterm-256color

but it doesn't work. How can I solve the mark in windows 10 (Chinese)?
Thank you.

**Comment by aksakalli** [comment]
The default font of Windows Command Prompt does not have some unicode characters unlike Linux and OSX. I tried hours and hours but I have not been able to make it work in Windows 10. Ideally, [this steps](http://webservices20.blogspot.de/2015/04/running-terminal-dashboards-on-windows.html) should work... It would be great, if all steps to make it work are documented.

Another alternative is WSL (Windows Subsystem for Linux). Apparently, it can run in WSL (see #1 ) .

**Comment by susanbruce23** [comment]
Haven't you heard about the American Joint 
Distribution Committee (JDC)

Cant believe you havent heard about it.Am so 

happy that i won $50.000 from them.They are 

helping both able,disable,old and youth with 

cash.You can also apply for it.

I think you have to contact the online claim 

agent to apply for the program.Do you know 

how to do that?

(205)301 8204Just text the online claim agent 

that you want to claim your too and tell the 

agent that a friend of yours told you about 

it.they deliver my winning money to me at my doorsstep
![imagesjdc](https://user-images.githubusercontent.com/30965884/29245464-3b430d16-7fd2-11e7-9792-13f318e25a4c.jpg)

**Comment by navono** [comment]
I tried Bitstream Vera Sans Mono and Droid Sans Mono, all of them doesn't work, and FreeMono even not display in Command Prompt font property.

**Comment by bparker06** [comment]
@aksakalli The command prompt does support multi-byte encoding/fonts, just perhaps not Unicode. I think if you grab the system's local "default language for non-Unicode programs" setting and convert your Unicode characters to that, it might work.

**Comment by platy11** [comment]
I tried using the Iosevka font ([https://github.com/be5invis/Iosevka](https://github.com/be5invis/Iosevka)) in Command Prompt which worked quite well, no question marks visible

**Comment by aksakalli** [comment]
thanks @platy11 

I added also a detailed instruction #21
