### ISSUE TITLE
Windows Command Prompt Font Support

### ISSUE THREAD

**Issue by aksakalli** [aksakalli/gtop#21]
The default font of Windows Command Prompt does not have some unicode characters unlike Linux and OSX. If you run with the default font `Consolas`, you will get a result like this:

![problem](https://user-images.githubusercontent.com/1939193/29266433-0d810784-80e5-11e7-80fa-58e6bbfcc5f1.png)

In this case, you need to change it to a Braille font:

## 1) Install Iosevka Font

- Download  [01-iosevka-1.13.2.zip](https://github.com/be5invis/Iosevka/releases/download/v1.13.2/01-iosevka-1.13.2.zip)
- Double click to `01-iosevka-1.13.2.zip\ttf\iosevka-regular.ttf`
- In the prompted window, click `Install`.

## 2) Add Iosevka to Command Prompt

- Open `Regedit` (`Win+R` type `regedit`)
- Open the following subkeys:

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Console\TrueTypeFont
```

- Add a new `String value` named zeros (if there is already `00`, new one should be `000`), and Data `Iosevka `:

![problem2](https://user-images.githubusercontent.com/1939193/29267289-4ee91eca-80e8-11e7-9d6e-b8ff18c30083.png)

## 3) Change Command Prompt Font

- Right click to Command Prompt's bar, go to `Properties`.
- Set Font as `Iosevka`

![untitled2](https://user-images.githubusercontent.com/1939193/29267444-055be8b8-80e9-11e7-9b56-5fbe230951f2.png)

## Result

![untitled3](https://user-images.githubusercontent.com/1939193/29267536-6a35bcd2-80e9-11e7-8019-04cee502b338.png)

**Comment by TheRealBastiaan** [comment]
I have the same issue on Windows 10. I made a Reg file with the font in one ZIP. Easy to use for new users.

[https://drive.google.com/file/d/0B9EkGjjyS2s0akZob3l3NlVfSTQ/view?usp=sharing](https://drive.google.com/file/d/0B9EkGjjyS2s0akZob3l3NlVfSTQ/view?usp=sharing)

**Comment by michaelmior** [comment]
Can this just be added to the wiki and the issue closed? It sounds like there's not directly a problem with gtop in this case.

**Comment by aksakalli** [comment]
@michaelmior ok, moved
