### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by Marcello168** [aksakalli/gtop#25]
#### Environment

- OS:i have install it but i don't know how to run it ,could you tell me
- Node version: (`$ node --version`)
- gtop version: (`$ npm info gtop version`)

#### Description

*A description of the issue*

**Comment by mike-bailey** [comment]
If you already installed it you should just be able to run `gtop`

**Comment by Marcello168** [comment]
![5b13a7a1-6c89-43f4-b9d5-788b0276586c](https://user-images.githubusercontent.com/20309676/29345301-78b6208e-8270-11e7-8d37-140ad7652acf.png)
 next step what should i do ？thanks

**Comment by mike-bailey** [comment]
Just run `gtop`

**Comment by Rafkat** [comment]
@mike-bailey 
I get error when running gtop:
/usr/bin/env: «node»: File or folder missing

**Comment by aksakalli** [comment]
@Rafkat did you install nodejs? apparently `node` binary is not in your `$PATH`.

* It is better to stick with [the official installment instructions for nodejs](https://nodejs.org/en/download/package-manager/). 

* Alternatively you can use [snap package manager](https://www.ubuntu.com/desktop/snappy) for Linux. (You don't need to install nodejs). 

After [installing snap](https://snapcraft.io/docs/core/install):

```
snap install gtop --edge --devmode
```

**Comment by Rafkat** [comment]
thanks, @aksakalli, installing (updating actually) resolved the issue.

**Comment by mike-bailey** [comment]
Recommend closing this issue if it's solved
