### ISSUE TITLE
Question: brew package?

### ISSUE THREAD

**Issue by michaelcurry** [aksakalli/gtop#27]
I would love to see this as a brew package.  https://brew.sh

I am not sure if this is planned, but think it could help a lot of people on the Mac side :+1:

**Comment by arguiot** [comment]
I think 🤔 it’s a great idea, I hope 🤞 @aksakalli will do it 😊

**Comment by aksakalli** [comment]
Hi,

@michaelcurry @arguiot I merged for snap package manager #2 

I am not familiar with OS X environment but I think we can add it to formula list in the repo like something similar to other npm packages:

- [jsonlint](https://github.com/Homebrew/homebrew-core/blob/32c6e0c82abc0e704e932bea1d12a498453eb3a2/Formula/jsonlint.rb)
- [write-good](https://github.com/Homebrew/homebrew-core/blob/af9cd86400b3b113b90d6ad734569f72b09f203a/Formula/write-good.rb)
- [bower](https://github.com/Homebrew/homebrew-core/blob/f8bd423166eaaf568b9ba508391a3fdb44e81daf/Formula/bower.rb)
- ...

You can try and send a pull request to the `Homebrew` for `gtop`

- [Contributing to Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)

**Comment by Alex-Keyes** [comment]
@aksakalli would it make more sense to submit this into the [Cask Homebrew](https://caskroom.github.io)?

**Comment by branchvincent** [comment]
With https://github.com/Homebrew/homebrew-core/pull/85344, this can now be closed!

**Comment by aksakalli** [comment]
> With [Homebrew/homebrew-core#85344](https://github.com/Homebrew/homebrew-core/pull/85344), this can now be closed!

That's great! Thank you @branchvincent
