### ISSUE TITLE
The sorting arrow indicator is upside down

### ISSUE THREAD

**Issue by mikeziri** [aksakalli/gtop#29]
#### Environment

- OS: macos
- Node version: 7.10.0
- gtop version: 0.1.5

#### Description

when pressing c,p or m for sorting cpu usage, process id and memory usage, the arrow is upside down.

**Comment by aksakalli** [comment]
Thanks for informing, the convention differs but It should be 

- `▲` for ascending 
- `▼` for descending

like in `Nautilus`:

![screenshot from 2017-08-22 22-19-44](https://user-images.githubusercontent.com/1939193/29586021-91ded8e4-8789-11e7-818b-2b67a680530c.png)

gtop `v0.1.5`:

![screenshot from 2017-08-22 22-24-17](https://user-images.githubusercontent.com/1939193/29586076-c19d150a-8789-11e7-8307-f696cb7af84b.png)

They needs to be swapped for the next version.
