### ISSUE TITLE
testing on synology

### ISSUE THREAD

**Issue by boistordu** [aksakalli/gtop#30]
#### Environment

- OS: synology DSM6x
- Node version: v4.8.4 
- gtop version: 0.1.5 

#### Description
too much cpu... suprisingly gtop work pretty good on synology. So I was wondering if we could test itwhich function of your app is eating so much cpu maybe? . it use around 80% of a dual core cpu on synology ds1512+

**Comment by aksakalli** [comment]
I am aware of performance issues and looking into. 

Duplicated #12
