### ISSUE TITLE
Lack of font in OSX

### ISSUE THREAD

**Issue by lkostrowski** [aksakalli/gtop#31]
#### Environment

- OS: macOS 10.12.6 Sierra
- Node version: 7.10.1
- gtop version: 0.1.5

#### Description

gtop interface lacks font(?) and shows question marks
Is there any dependency font needed?

<img width="1258" alt="image 2017-08-21 at 12 02 48 pm" src="https://user-images.githubusercontent.com/9268745/29514521-2dea2ed6-8669-11e7-8dc6-e9b15d2010d0.png">

**Comment by aksakalli** [comment]
The default Terminal font should support these characters, have you tried to run it as:

```
LANG=en_US.utf8 TERM=xterm-256color gtop
```

**Comment by lkostrowski** [comment]
It works. The problem was with LANG
Thanks
