### ISSUE TITLE
How to install over RHEL 6

### ISSUE THREAD

**Issue by dineshrathee12** [aksakalli/gtop#33]
Hey Ali,

I am handling infrastructure operations and it would be really helpful for us ; Could you please suggest us full procedure to implement over RHEL 6 Servers having local yum repository and suggest me about Node.js installation ..

Will there be any amount of resources consumption installing this ? Any possible impact ( if any ) ?

Regards,
Dinesh Rathee

**Comment by aksakalli** [comment]
You need to have `Node.js >= v4` please refer to [the official node documentation](https://nodejs.org/en/download/package-manager/) for installation.

--

Alternatively, you can install it using [snap](https://snapcraft.io/docs/core/install). 

```
snap install gtop --edge --devmode
```

Frankly, I have no intention to distribute it over every single package manager possible. It is not even the case for nodejs itself...
