### ISSUE TITLE
Question: gtop and top

### ISSUE THREAD

**Issue by snakezzl** [aksakalli/gtop#35]
#### Environment

- OS: CentOS Linux release 7.3.1611 (Core)
- Node version: (`$ node --version`) v7.10.0
- gtop version: (`$ npm info gtop version`) 0.1.5

#### Description

When i run "gtop" and "top" command respectively (almostly run at the same time in two terminals) ,
i found that the value in "%CPU" column for mysql process is very different, below is the screenshot.
Could you explain this to me?

<img width="1440" alt="2017-08-24 15 00 33" src="https://user-images.githubusercontent.com/343500/29653617-2d1be528-88dd-11e7-9624-dd26f903959a.png">
<img width="1440" alt="2017-08-24 15 00 35" src="https://user-images.githubusercontent.com/343500/29653618-2d1cb944-88dd-11e7-9833-a4c2b61f5d8e.png">

**Comment by aksakalli** [comment]
`top` command shows usage per single core in _Irix mode_ (default), that's why it is sometimes more than 100%. (You can toggle _Irix mode_ by pressin `Shift` + `i`)

However, `gtop` always shows the usage proportional to the overall CPU resource.

**Comment by snakezzl** [comment]
Hi @aksakalli, thanks for your detailed answer. That helps me a lot.
