### ISSUE TITLE
Windows Subsystem for Linux Characters Showing Question-Mark Boxes

### ISSUE THREAD

**Issue by jsd1710** [aksakalli/gtop#36]
#### Environment

- OS: Windows 10 Version 1703 Build 16251.1002 / Bash on Ubuntu on Windows, Ubuntu 16.04 Kernel 4.4.0-43-Microsoft
- Node version: 4.2.6
- gtop version: 0.1.5
- commandline: LANG=en_US.utf8 TERM=xterm-256color /usr/bin/nodejs /usr/local/bin/gtop

#### Description

When running gtop on the Windows Subsystem for Linux, there are improper characters being printed, despite the definition of environment variables LANG and TERM.
![image](https://user-images.githubusercontent.com/2375180/29675404-e7435a8c-88a9-11e7-811a-eefe9c11a4ad.png)

**Comment by aksakalli** [comment]
seems like a font related issues, please also check:

- https://github.com/aksakalli/gtop/issues/1#issuecomment-321857777
- https://github.com/aksakalli/gtop/issues/21
