### ISSUE TITLE
FACING below Issue during installation

### ISSUE THREAD

**Issue by dineshrathee12** [aksakalli/gtop#37]
#### Environment

- OS:
- Node version: (`$ node --version`)
- gtop version: (`$ npm info gtop version`)

node v4.2.1
npm  v2.14.7

#### Description

npm ERR! Linux 2.6.32-696.3.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gtop" "-g"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 151.101.0.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/gtop-master/npm-debug.log

ERROR LOG
==========>
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'gtop',
1 verbose cli   '-g' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'gtop', null ]
7 verbose cache add spec gtop
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'gtop',
8 silly cache add   scope: null,
8 silly cache add   name: 'gtop',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed gtop@*
10 verbose addNamed "*" is a valid semver range for gtop
11 silly addNameRange { name: 'gtop', range: '*', hasData: false }
12 silly mapToRegistry name gtop
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/gtop
16 verbose addNameRange registry:https://registry.npmjs.org/gtop not in flight; fetching
17 verbose request uri https://registry.npmjs.org/gtop
18 verbose request no auth needed
19 info attempt registry request try #1 at 1:45:15 AM
20 verbose request id 75c0d36eb8f37d7b
21 http request GET https://registry.npmjs.org/gtop
22 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.0.162:443
23 info attempt registry request try #2 at 1:46:28 AM
24 http request GET https://registry.npmjs.org/gtop
25 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.52.162:443
26 info attempt registry request try #3 at 1:48:32 AM
27 http request GET https://registry.npmjs.org/gtop
28 verbose stack Error: connect ETIMEDOUT 151.101.0.162:443
28 verbose stack     at Object.exports._errnoException (util.js:874:11)
28 verbose stack     at exports._exceptionWithHostPort (util.js:897:20)
28 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
29 verbose cwd /tmp/gtop-master
30 error Linux 2.6.32-696.3.1.el6.x86_64
31 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gtop" "-g"
32 error node v4.2.1
33 error npm  v2.14.7
34 error code ETIMEDOUT
35 error errno ETIMEDOUT
36 error syscall connect
37 error network connect ETIMEDOUT 151.101.0.162:443
37 error network This is most likely not a problem with npm itself
37 error network and is related to network connectivity.
37 error network In most cases you are behind a proxy or have bad network settings.
37 error network
37 error network If you are behind a proxy, please make sure that the
37 error network 'proxy' config is set properly.  See: 'npm help config'
38 verbose exit [ 1, true ]

**Comment by aksakalli** [comment]
it is a network error as the message states.

**Comment by dineshrathee12** [comment]
Resolution pls ? Any specific port or something ?

**Comment by pascalandy** [comment]
Works good here.
