### ISSUE TITLE
Font issues

### ISSUE THREAD

**Issue by michapixel** [aksakalli/gtop#38]
For all those with corrupted/wrong font output:

extending gtop.js with following  @ line 4
```
if (process.platform === 'win32') {
  process.env.TERM = 'windows-ansi'
}
```
should ~~fix~~ temper this issues, at least it does so for me. 

before:
![conemu64_2017-08-25_17-30-32](https://user-images.githubusercontent.com/370877/29720807-5ab084d8-89bb-11e7-8a8d-3c9483a691d1.png)

after:
![conemu64_2017-08-25_17-29-34](https://user-images.githubusercontent.com/370877/29720771-3635f0d4-89bb-11e7-88cb-73c6f10a0dcd.png)

**Comment by darabos** [comment]
I had the same issue with the borders on Ubuntu 16.04's Gnome Terminal. Running with `TERM=windows-ansi gtop` has (absurdly) fixed it. I did not have the other issues visible on your screenshots, so it's all perfect now! Thanks!

**Comment by verajosemanuel** [comment]
Very absurd!!. Here Ubuntu Server solved the issue 'Windows-ansi' except the Network history pane

**Comment by diethnis** [comment]
Running arch with some language fonts installed, gtop braille shows up as boxes with `TERM=screen.xterm-256-color, screen,` or `xterm-256color` through tilda. The braille shows up fine in xterm/uxterm with `TERM=xterm` though.

**Comment by grantcarthew** [comment]
I had to do the following when using Putty to fix it:
Set the 'Connection > Data > 'Terminal-type string' to 'putty' instead of 'xterm'.
From this post: https://serverfault.com/questions/475925/how-to-fix-putty-showing-garbled-characters

**Comment by AgnibhaBose** [comment]
Facing the same issue in `elementary OS 5.0 Juno`
![Font's Issue](https://user-images.githubusercontent.com/25074872/51086096-236e9c80-1768-11e9-8c21-e4a644125521.png)

Any Idea how to fix this?

**Comment by aksakalli** [comment]
```
$ LANG=en_US.utf8 TERM=xterm-256color gtop
```
should fix the issue for Linux
