### ISSUE TITLE
Vertical alignment issues on 4k monitor

### ISSUE THREAD

**Issue by Olian04** [aksakalli/gtop#40]
(first of all, gtop is beautiful, absolutely stunning)

#### Environment

- OS: Ubuntu 17.04
- Screen res: 4k
- Node version: 8.4.0
- gtop version: 0.1.5

#### Description

There are some vertical alignment issues with the green bounding boxes when drawn on a 4k monitor.
Specifically the lower portions of "Swap" and "Disk Usage".
![](https://i.imgur.com/n3TFEbA.png)

**Comment by aksakalli** [comment]
Hi, `swap` & `memory` has the same height percentage. Since only one is remained, it is not used by any of it. (It is not drawn as bitmap, rather as text lines)
