### ISSUE TITLE
Color schemes?

### ISSUE THREAD

**Issue by domgregori** [aksakalli/gtop#43]
#### Environment

- OS:
- Node version: (`4.8.3`)
- gtop version: (`0.1.5`)

#### Description

The colors in the README screenshot are different than the default. What colors are you using and where did you change it? Also for the network chart, mine are coming up as empty boxes instead of bars. I tried using `LANG=en_US.utf8 TERM=xterm-256color gtop`.

**Comment by aksakalli** [comment]
@domgregori the gif file was taken from Ubuntu 16.04 default `Terminal Emulator`. Maybe you have a different color scheme for your terminal..
