### ISSUE TITLE
CPU & Memory graphs missing top few lines

### ISSUE THREAD

**Issue by dgoodlad** [aksakalli/gtop#44]
#### Environment

- OS: Linux (debian stretch)
- Node version: 8.1.2
- gtop version: 0.1.5

#### Description

The CPU & Memory history graphs seem to be vertically offset by a couple of lines, leaving 2-3 empty rows below the `0` row, and missing the `100` row at the top. Here's a screenshot:

![image](https://user-images.githubusercontent.com/399/30834428-68815d64-a296-11e7-8b26-bc730d0c3d8a.png)

This happens consistently regardless of how large I make the terminal window.

**Comment by basepi** [comment]
I seem to be hitting the same thing.

**Comment by aksakalli** [comment]
One extra row is reserved for x labels regardless of being set. It is an issue related to [blessed-contrib](https://github.com/yaronn/blessed-contrib)
