### ISSUE TITLE
Need sudo ..please change the front page instruction

### ISSUE THREAD

**Issue by unixbhaskar** [aksakalli/gtop#45]
#### Environment

- OS: Archlinux
- Node version: (`$ node --version`) v8.5.0

- gtop version: (`$ npm info gtop version`) 0.1.5

*A description of the issue*
#### Description
It requires sudo to get it done...see the output below:
`bhaskar@ArchLinux_17:46:56_Tue Sep 26:~>npm install gtop -g
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bhaskar/.npm/_logs/2017-09-26T12_17_18_921Z-debug.log
bhaskar@ArchLinux_17:47:19_Tue Sep 26:~>sudo npm install gtop -g
/usr/bin/gtop -> /usr/lib/node_modules/gtop/bin/gtop
+ gtop@0.1.5
added 106 packages in 55.947s
`

**Comment by aksakalli** [comment]
duplicated #14
