### ISSUE TITLE
Feature request: facilities to keep old data

### ISSUE THREAD

**Issue by sas05** [aksakalli/gtop#46]
No doubt abut that gtop is a handy tool. I think, to have an extension to keep old record and filtering would be value added for gtop

**Comment by aksakalli** [comment]
I don't have plans to implement such functionality, personally I use [prometheus](https://prometheus.io/) or [cAdvisor](https://github.com/google/cadvisor) + [InfluxDB](https://github.com/influxdata/influxdb) along with [grafana](https://grafana.com/) to visualize for servers.
