### ISSUE TITLE
graph are comming ???? on ubuntu

### ISSUE THREAD

**Issue by sas05** [aksakalli/gtop#48]
#### Environment

- OS: ubuntu 17.04
- Node version: 7.10.1
- gtop version: latest

#### Description

![screen shot 2017-09-26 at 17 28 34](https://user-images.githubusercontent.com/775100/30868989-57d43e4c-a2e0-11e7-91d5-dc9cfca79a3f.png)

**Comment by aksakalli** [comment]
please try to run it as:

`LANG=en_US.utf8 TERM=xterm-256color gtop`

**Comment by sas05** [comment]
Thanks 👍
