### ISSUE TITLE
Feature request: Precompiled binary

### ISSUE THREAD

**Issue by mholt** [aksakalli/gtop#51]
I might be interested in using this in our research lab. But our systems are pretty delicately configured; to avoid risking any problems (among other reasons), I am not inclined to install Node/npm. But I would happily run a binary. Would you consider packaging up some Linux binaries for each release? Or is there a typical way of compiling JS apps to binary form for distribution?

**Comment by aksakalli** [comment]
hi @mholt ,

maybe we can use something like [pkg](https://github.com/zeit/pkg) to create binary builds.

Also there already exists a [snap](https://www.ubuntu.com/desktop/snappy) package for [gtop](https://build.snapcraft.io/user/aksakalli/gtop):

```
sudo snap install --edge gtop 
```

**Comment by mholt** [comment]
Sounds good to me, thanks! Does the snap install npm and stuff locally or does it just plop the binary in the PATH?

**Comment by aksakalli** [comment]
Snap packages or their dependencies do not affect your system:

from https://snapcraft.io/docs/snaps/intro

> ## What is a snap?
> 
> A snap :
> 
> - is a squashFS filesystem containing your app code and a snap.yaml file containing specific metadata. It has a read-only file-system and, once installed, a writable area.
> - is self-contained. __It bundles most of the libraries and runtimes it needs and can be updated and reverted without affecting the rest of the system.__
> - is confined from the OS and other apps through security mechanisms, but can exchange content and functions with other snaps according to fine-grained policies controlled by the user and the OS defaults.
>

**Comment by mholt** [comment]
Ah, thanks!
