### ISSUE TITLE
Can I use this with Conky?

### ISSUE THREAD

**Issue by mksglu** [aksakalli/gtop#56]
I want to use my desktop in my background. As a wallpaper.

#### Environment

- OS:
- Node version: v8.6.0
- gtop version: 0.1.5

#### Description

*Can I use it with Conky?

**Comment by aksakalli** [comment]
Hi @mkoseoglu,

You can install [tilda terminal](https://github.com/lanoxx/tilda) which can run in the background.

```
sudo apt-get install tilda
``` 

I configure it to launch `gtop` as default command and changed some other style settings (my [config_0](https://gist.github.com/aksakalli/29b6de2f3ea6fa9a42f31346e5a4a0c4)). You can configure `tilda` by:

```
wget -O ~/.config/tilda/config_0 https://gist.githubusercontent.com/aksakalli/29b6de2f3ea6fa9a42f31346e5a4a0c4/raw/config_0

```

and start it 

```
tilda
```

![screenshot from 2017-10-06 11-05-19](https://user-images.githubusercontent.com/1939193/31271824-24f41154-aa89-11e7-9d34-82a65f0283c0.png)

_optionally you can add it to `Startup Applications` to start it automatically when you log in_

```
wget -O ~/.config/autostart/tilda.desktop https://gist.githubusercontent.com/aksakalli/29b6de2f3ea6fa9a42f31346e5a4a0c4/raw/tilda.desktop
```

**Comment by mkoseoglu** [comment]
Thank u responsive. @aksakalli 
Linux is not working properly on I3WM. I got an error in the terminal.
`(tilda:3352): Vte-CRITICAL **: void vte_terminal_set_colors(VteTerminal*, const GdkRGBA*, const GdkRGBA*, const GdkRGBA*, gsize): assertion 'background == nullptr || valid_color(background)' failed`
`Tilda has started. Press F1 to pull down the window.`
`(tilda:3352): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkNotebook'`
`(tilda:3352): Gtk-CRITICAL **: gtk_notebook_get_n_pages: assertion 'GTK_IS_NOTEBOOK (notebook)' failed`
![ss](https://www.mkoseoglu.com/wp-content/uploads/2017-10-06-125209_1920x1080_scrot-768x432.png)
