### ISSUE TITLE
MaxY value too small to show 100

### ISSUE THREAD

**Issue by felleg** [aksakalli/gtop#59]
#### Environment

- OS: Ubuntu 16.04
- Node version: v4.2.6
- gtop version: 0.1.5

#### Description

I noticed that the graphs in gtop would not plot values above ~80% (see attached picture). This can be fixed by changing the value of MaxY from 100 to 125 [here](https://github.com/aksakalli/gtop/blob/master/lib/gtop.js), however I don't really know if that's the proper way to fix this bug.
![screenshot from 2017-10-30 14-59-11](https://user-images.githubusercontent.com/7781739/32190096-148e81de-bd83-11e7-90f8-e8fe2d50cf8b.png)

**Comment by aksakalli** [comment]
percentage per core shouldn't be more than 100%, I think that should have been fixed with the new version of `systeminformation`
