### ISSUE TITLE
Graphs only drawing background colors.

### ISSUE THREAD

**Issue by WalkerGriggs** [aksakalli/gtop#69]
#### Environment

- OS: Debian 9
- Node version: v6.12.0
- gtop version: 0.1.5
- terminal: XTerm

#### Description

Graphs are not displaying, but I can see their 'background' when I go to highlight the area. I have tried changing colors set in Xresources. **Do note:** this is only an issue in XTerm. When I swap to gnome-sensible-term, gtop functions as intended. 

I run gtop with the recommended command:
``` LANG=en_US.utf8 TERM=xterm-256color gtop```

![gtop_1](https://user-images.githubusercontent.com/12417470/33809042-6d91e180-ddbe-11e7-8d0a-5d7ceba6cbbf.png)

But when I go to highlight the graphs, you can see that it's actually the foreground not drawing. The background is drawing just fine. This makes me think that it's specifically a xterm foreground rendering issue.

![gtop_2](https://user-images.githubusercontent.com/12417470/33809041-6d5fd8ac-ddbe-11e7-8c1e-23fba067c3ef.png)

**Comment by aksakalli** [comment]
it could be a problem with your color pallet? also there is an existing feature request to define the colors #62
