### ISSUE TITLE
Errors on Archlinux/urxvt

### ISSUE THREAD

**Issue by bastelfreak** [aksakalli/gtop#72]
#### Environment

- OS: Archlinux
- Node version: v9.8.0
- gtop version: 0.1.5

#### Description

I use urxvt as my main terminal. I get the error/warning during the start if gtop:

```
$  gtop 

Error on rxvt-256color.plab_norm:
";7%;%?%p4%t;5%;m%?%p9%t\u000e%e\u000f%;"

var v,
 stack = [],
 out = [];
out.push(";
7")};
if ((stack.push(v = params[3]),
 v)) {out.push(";
5")}out.push("m");
if ((stack.push(v = params[8]),
 v)) {out.push("\x0e")} else {out.push("\x0f")};
return out.join("");
```

However, gtop seems to work fine. I don't get the error if I manipulate TERM:

```
$ TERM=xterm-256color gtop
```

Let me know if you need any additional information.

**Comment by aksakalli** [comment]
apparently, you need the `TERM` variable in your setup.
