### ISSUE TITLE
Network History does not resize

### ISSUE THREAD

**Issue by imbsky** [aksakalli/gtop#78]
#### Environment

- OS: macOS 10.13.6
- Node version: v8.11.3
- gtop version: 0.1.5

#### Description

Hi,
Network History does not resize.
<img width="1280" alt="screen shot 2018-07-25 at 18 33 14" src="https://user-images.githubusercontent.com/38746192/43192789-4a637c18-9039-11e8-9368-c1dd45eccdbe.png">

**Comment by aksakalli** [comment]
it was designed to represent every sample in terms of one character regardless of the screen/widget size.
