### ISSUE TITLE
Network History without transfared data on Ubuntu 18.04

### ISSUE THREAD

**Issue by aberlin** [aksakalli/gtop#80]
#### Environment

- OS: Ubuntu 18.04 bionic
 Kernel: x86_64 Linux 4.15.0-34-generic
 Shell: bash 4.4.19

- Node version: (`v10.11.0`)
- gtop version: (` 1.0.0`)

#### Description

I have just installed node and then gtop with npm. 
But now the Network History is without a transfared data graph.
I have no experience with node so it is maybe an obvious error.

**Comment by aksakalli** [comment]
maybe it is due to the number of lines in your terminal screen. It disappears when there is no enough space.

**Comment by aberlin** [comment]
you are right, that was an easy one ¯\_(ツ)_/¯
