### ISSUE TITLE
Question marks are still appearing

### ISSUE THREAD

**Issue by AlexiRJamal** [aksakalli/gtop#83]
#### Environment

- OS: Windows 10
- Node version: 8.11
- gtop version: (1.0.0)

#### Description
Question marks are appearing. I tried changing the `LANG` and `TERM` but I don't know how to do it. I went into the `npm/gtop` folder in `AppData` and typed `@SET LANG=as defined` and so with `TERM` but it still appears.
Any help on how to actually do it?

**Comment by cluzier** [comment]
I am having the same issue. Hoping someone answers.

**Comment by aksakalli** [comment]
In Windows, you can try installing fonts.
http://webservices20.blogspot.com/2015/04/running-terminal-dashboards-on-windows.html
