### ISSUE TITLE
Question: gtop display problem 

### ISSUE THREAD

**Issue by DanteRL** [aksakalli/gtop#88]
#### Environment

- OS: CentOS
- Node version: (`$ node --version`)
- gtop version: (`$ npm info gtop version`)

#### Description
![image](https://user-images.githubusercontent.com/23353256/56267883-ad8d1f00-6122-11e9-9152-71136faeb2e1.png)

*A description of the issue*
what should I do with this problem?

**Comment by aksakalli** [comment]
use
```
LANG=en_US.utf8 TERM=xterm-256color gtop
```

as described in the `README`.
